export const COLORS = {
  WHITE: '#fff',
  SIDE_PANEL_PRIMARY: '#022028',
  SIDE_PANEL_HIGHLIGHTED: '#1F4148',
  RIGHT_INVESTMENTS_BUTTON: '#CCE8E7',
  RIGHT_ADD_INVESTMENT_BUTTON: '#022028'
};

export default COLORS;
